### ISSUE TITLE
NativeGCMCipherException: The message could not be decrypted successfully.It has either been tampered with or the wrong resource is being decrypted.

### ISSUE THREAD

**Issue by ir2pid** [facebook/conceal#131]
When I kill the app and restart, decrypting gives the error: 

`NativeGCMCipherException: The message could not be decrypted successfully.It has either been tampered with or the wrong resource is being decrypted.`

the encryption and decryption works only when the app is in memory, killing it gives decryption error on the next run
using SharedPrefsBackedKeyChain and SystemNativeCryptoLibrary to get the Crypto instance.

**Comment by siyengar** [comment]
Could you paste a sample of the code that you are using to call conceal.

**Comment by ir2pid** [comment]
```

    public static String CRYPTO_ERROR = "CRYPTO_ERROR";
    public static String CRYPTO_ENCODING_FORMAT = "ISO-8859-1";
    public static String CRYPTO_ENTITY_KEY = "CRYPTO_ENTITY_KEY";

    public String encrypt(Context context, String input) {
        byte[] cipherText = null;
        String output = null;
        try {
            Crypto crypto = getCrypto(context);
            cipherText = crypto.encrypt(input.getBytes(CRYPTO_ENCODING_FORMAT), new Entity(CRYPTO_ENTITY_KEY));
            output = new String(cipherText, CRYPTO_ENCODING_FORMAT);
            return output;
        } catch (KeyChainException e) {
            e.printStackTrace();
        } catch (CryptoInitializationException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public String decrypt(Context context, String input) {
        String output = null;
        byte[] cipherText = null;
        try {
            cipherText = getCrypto(context).decrypt(input.getBytes(CRYPTO_ENCODING_FORMAT), new Entity(CRYPTO_ENTITY_KEY));
            output = new String(cipherText, CRYPTO_ENCODING_FORMAT);
        } catch (KeyChainException e) {
            e.printStackTrace();
        } catch (CryptoInitializationException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return output;
    }
    private static Crypto getCrypto(Context context) {
        Crypto crypto = new Crypto(
                new SharedPrefsBackedKeyChain(context),
                new SystemNativeCryptoLibrary());

        if (crypto.isAvailable()) {
            return crypto;
        } else {
            return null;
        }
    }

```

**Comment by originx** [comment]
Hi,

We just noticed the same issue.
Killing the app is the way to reproduce it, we do it programatically since we have some sort of "Enviroment switcher" in our app where we switch between endpoints and the kill/restart the app to apply the changes.

Version of conceal used 1.0.5
Code is pretty much simmilar to @ir2pid snippet and we have the same exception.

Could it be that the data gets corrupted if reading is interrupted abruptly?

**Comment by helios175** [comment]
Thanks! I'll try to repro in a moment. Let's find out where the problem is!

**Comment by helios175** [comment]
Just a check: could you please add this to getCrypto? Just to check the key is still the same:

getCrypto()
KeyChain keychain = new SharedPrefsKeyChain(...);
byte[] key = keyChain.getKey();
android.util.Log.d("KEY", "----");
for (byte b: key) {
Just a check: could you please add this to getCrypto? Just to check the key is still the same:

```
KeyChain keychain = new SharedPrefsKeyChain(...);
byte[] key = keyChain.getKey();
android.util.Log.d("KEY", "----");
for (byte b: key) {
  android.util.Log.d("KEY", "" + b);
}
```

I want to ensure the key is still the same.
Thanks!

**Comment by helios175** [comment]
Errr... wait a minute.
When encoding are you converting to string again? In the failing code?
That's a problem because you're using an encoding that won't accept any byte combination. And any encrypted string will be random bytes. Any byte combination can be equally probably. So that can change the interpretation of the bytes, and when to convert the parsed string to bytes... it will change.

If you need to convert to string use hexa, or base64 which will faithfully represent the bytes.

If this was only for show purposes... tell me how you handle the cipherBytes for real.
I will make a test storing those bytes into a file and reading from there.

**Comment by originx** [comment]
We encode the data we use using Base64, code we use can be found in following gist:
https://gist.github.com/originx/decc81dda169a13731bb42b89c1a12a4

We use GSON, Conceal and SharedPrefs as storage
I will try to add the snippet you suggested and get back to you

**Comment by originx** [comment]
Regarding the Key(s) of course they are different since we clear shared prefs and all app data before restarting the app.

This should clear all data, keys and rest of the data stored with the application and after clearing we call to restart the app and reinitialize everything:

` Process.killProcess(Process.myPid());`

`04-04 20:41:27.238 31646-31646/D/CIPHER KEY: ----
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: 7
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: 3
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: 80
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: -106
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: 9
04-04 20:41:27.238 31646-31646/D/CIPHER KEY: -61
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -92
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -93
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: 33
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: 127
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: 47
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -123
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: 68
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -90
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -42
04-04 20:41:27.239 31646-31646/D/CIPHER KEY: -122


04-04 20:41:27.239 31646-31646/D/MAC KEY: ----
04-04 20:41:27.239 31646-31646/D/MAC KEY: 90
04-04 20:41:27.239 31646-31646/D/MAC KEY: 120
04-04 20:41:27.239 31646-31646/D/MAC KEY: 66
04-04 20:41:27.239 31646-31646/D/MAC KEY: 30
04-04 20:41:27.239 31646-31646/D/MAC KEY: -75
04-04 20:41:27.239 31646-31646/D/MAC KEY: 19
04-04 20:41:27.239 31646-31646/D/MAC KEY: 74
04-04 20:41:27.239 31646-31646/D/MAC KEY: 76
04-04 20:41:27.239 31646-31646/D/MAC KEY: 102
04-04 20:41:27.239 31646-31646/D/MAC KEY: 20
04-04 20:41:27.239 31646-31646/D/MAC KEY: 54
04-04 20:41:27.239 31646-31646/D/MAC KEY: 71
04-04 20:41:27.239 31646-31646/D/MAC KEY: -7
04-04 20:41:27.239 31646-31646/D/MAC KEY: 91
04-04 20:41:27.239 31646-31646/D/MAC KEY: -80
04-04 20:41:27.239 31646-31646/D/MAC KEY: -109
04-04 20:41:27.239 31646-31646/D/MAC KEY: 64
04-04 20:41:27.239 31646-31646/D/MAC KEY: 112
04-04 20:41:27.239 31646-31646/D/MAC KEY: 70
04-04 20:41:27.239 31646-31646/D/MAC KEY: 98
04-04 20:41:27.239 31646-31646/D/MAC KEY: -76
04-04 20:41:27.239 31646-31646/D/MAC KEY: 31
04-04 20:41:27.239 31646-31646/D/MAC KEY: -18
04-04 20:41:27.239 31646-31646/D/MAC KEY: -98
04-04 20:41:27.239 31646-31646/D/MAC KEY: 106
04-04 20:41:27.239 31646-31646/D/MAC KEY: -77
04-04 20:41:27.239 31646-31646/D/MAC KEY: 123
04-04 20:41:27.239 31646-31646/D/MAC KEY: 87
04-04 20:41:27.239 31646-31646/D/MAC KEY: 35
04-04 20:41:27.239 31646-31646/D/MAC KEY: 120
04-04 20:41:27.239 31646-31646/D/MAC KEY: -11
04-04 20:41:27.240 31646-31646/D/MAC KEY: -76
04-04 20:41:27.240 31646-31646/D/MAC KEY: 106
04-04 20:41:27.240 31646-31646/D/MAC KEY: -111
04-04 20:41:27.240 31646-31646/D/MAC KEY: 126
04-04 20:41:27.240 31646-31646/D/MAC KEY: 47
04-04 20:41:27.240 31646-31646/D/MAC KEY: 73
04-04 20:41:27.240 31646-31646/D/MAC KEY: 90
04-04 20:41:27.240 31646-31646/D/MAC KEY: 38
04-04 20:41:27.240 31646-31646/D/MAC KEY: 124
04-04 20:41:27.240 31646-31646/D/MAC KEY: -32
04-04 20:41:27.240 31646-31646/D/MAC KEY: 42
04-04 20:41:27.240 31646-31646/D/MAC KEY: 56
04-04 20:41:27.240 31646-31646/D/MAC KEY: -94
04-04 20:41:27.240 31646-31646/D/MAC KEY: -110
04-04 20:41:27.240 31646-31646/D/MAC KEY: -60
04-04 20:41:27.240 31646-31646/D/MAC KEY: 61
04-04 20:41:27.240 31646-31646/D/MAC KEY: 45
04-04 20:41:27.240 31646-31646/D/MAC KEY: -102
04-04 20:41:27.240 31646-31646/D/MAC KEY: -14
04-04 20:41:27.240 31646-31646/D/MAC KEY: 111
04-04 20:41:27.240 31646-31646/D/MAC KEY: -109
04-04 20:41:27.240 31646-31646/D/MAC KEY: 62
04-04 20:41:27.240 31646-31646/D/MAC KEY: 57
04-04 20:41:27.240 31646-31646/D/MAC KEY: 11
04-04 20:41:27.240 31646-31646/D/MAC KEY: 126
04-04 20:41:27.240 31646-31646/D/MAC KEY: 55
04-04 20:41:27.240 31646-31646/D/MAC KEY: 65
04-04 20:41:27.240 31646-31646/D/MAC KEY: 58
04-04 20:41:27.240 31646-31646/D/MAC KEY: 80
04-04 20:41:27.240 31646-31646/D/MAC KEY: 60
04-04 20:41:27.240 31646-31646/D/MAC KEY: 16
04-04 20:41:27.240 31646-31646/D/MAC KEY: 12
04-04 20:41:27.240 31646-31646/D/MAC KEY: -38


—SECOND RUN

04-04 20:44:51.469 3962-3962/D/CIPHER KEY: ----
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -123
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -100
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 90
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 112
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -6
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 24
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 78
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -21
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -108
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 46
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -69
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 7
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -98
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: 124
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -44
04-04 20:44:51.469 3962-3962/D/CIPHER KEY: -40

04-04 20:44:51.469 3962-3962/D/MAC KEY: ----
04-04 20:44:51.469 3962-3962/D/MAC KEY: -85
04-04 20:44:51.469 3962-3962/D/MAC KEY: 82
04-04 20:44:51.469 3962-3962/D/MAC KEY: 63
04-04 20:44:51.469 3962-3962/D/MAC KEY: 81
04-04 20:44:51.469 3962-3962/D/MAC KEY: 55
04-04 20:44:51.469 3962-3962/D/MAC KEY: 113
04-04 20:44:51.469 3962-3962/D/MAC KEY: -85
04-04 20:44:51.469 3962-3962/D/MAC KEY: 81
04-04 20:44:51.469 3962-3962/D/MAC KEY: 15
04-04 20:44:51.469 3962-3962/D/MAC KEY: 46
04-04 20:44:51.469 3962-3962/D/MAC KEY: -65
04-04 20:44:51.469 3962-3962/D/MAC KEY: -109
04-04 20:44:51.469 3962-3962/D/MAC KEY: 32
04-04 20:44:51.469 3962-3962/D/MAC KEY: 12
04-04 20:44:51.469 3962-3962/D/MAC KEY: 16
04-04 20:44:51.469 3962-3962/D/MAC KEY: 97
04-04 20:44:51.469 3962-3962/D/MAC KEY: 45
04-04 20:44:51.469 3962-3962/D/MAC KEY: 112
04-04 20:44:51.469 3962-3962/D/MAC KEY: 11
04-04 20:44:51.470 3962-3962/D/MAC KEY: -16
04-04 20:44:51.470 3962-3962/D/MAC KEY: -93
04-04 20:44:51.470 3962-3962/D/MAC KEY: -73
04-04 20:44:51.470 3962-3962/D/MAC KEY: -75
04-04 20:44:51.470 3962-3962/D/MAC KEY: 89
04-04 20:44:51.470 3962-3962/D/MAC KEY: 100
04-04 20:44:51.470 3962-3962/D/MAC KEY: -28
04-04 20:44:51.470 3962-3962/D/MAC KEY: 59
04-04 20:44:51.470 3962-3962/D/MAC KEY: 5
04-04 20:44:51.470 3962-3962/D/MAC KEY: 124
04-04 20:44:51.470 3962-3962/D/MAC KEY: -124
04-04 20:44:51.470 3962-3962/D/MAC KEY: -50
04-04 20:44:51.470 3962-3962/D/MAC KEY: -33
04-04 20:44:51.470 3962-3962/D/MAC KEY: -82
04-04 20:44:51.470 3962-3962/D/MAC KEY: -23
04-04 20:44:51.470 3962-3962/D/MAC KEY: 58
04-04 20:44:51.470 3962-3962/D/MAC KEY: -50
04-04 20:44:51.470 3962-3962/D/MAC KEY: 98
04-04 20:44:51.470 3962-3962/D/MAC KEY: -57
04-04 20:44:51.470 3962-3962/D/MAC KEY: 30
04-04 20:44:51.470 3962-3962/D/MAC KEY: -31
04-04 20:44:51.470 3962-3962/D/MAC KEY: -42
04-04 20:44:51.470 3962-3962/D/MAC KEY: 91
04-04 20:44:51.470 3962-3962/D/MAC KEY: -67
04-04 20:44:51.470 3962-3962/D/MAC KEY: 16
04-04 20:44:51.470 3962-3962/D/MAC KEY: 112
04-04 20:44:51.470 3962-3962/D/MAC KEY: -60
04-04 20:44:51.470 3962-3962/D/MAC KEY: -58
04-04 20:44:51.470 3962-3962/D/MAC KEY: -25
04-04 20:44:51.470 3962-3962/D/MAC KEY: 71
04-04 20:44:51.470 3962-3962/D/MAC KEY: -90
04-04 20:44:51.470 3962-3962/D/MAC KEY: 73
04-04 20:44:51.470 3962-3962/D/MAC KEY: 94
04-04 20:44:51.470 3962-3962/D/MAC KEY: -91
04-04 20:44:51.470 3962-3962/D/MAC KEY: -8
04-04 20:44:51.470 3962-3962/D/MAC KEY: 10
04-04 20:44:51.470 3962-3962/D/MAC KEY: 72
04-04 20:44:51.470 3962-3962/D/MAC KEY: 7
04-04 20:44:51.470 3962-3962/D/MAC KEY: -40
04-04 20:44:51.470 3962-3962/D/MAC KEY: -16
04-04 20:44:51.470 3962-3962/D/MAC KEY: -27
04-04 20:44:51.470 3962-3962/D/MAC KEY: -67
04-04 20:44:51.470 3962-3962/D/MAC KEY: -118
04-04 20:44:51.470 3962-3962/D/MAC KEY: 117
04-04 20:44:51.471 3962-3962/D/MAC KEY: 94
                                                                        
                                                                        --------- beginning of crash`

**Comment by helios175** [comment]
Ok, so that's the problem. The SharedPrefsKeyChain is an implementation that uses shared preferences to store the needed key to decrypt.

You can either not remove that value, or store that secret somewhere else.

The current implementation just generates a new one when nothing is found. But you can change the implementation very easily (extending or just implementing the interface).

**Comment by originx** [comment]
Hmm but my intention is to wipe everything and regenerate the keys and create new storage, actually it works as I would want it.
I will double check tomorrow in the morning is something accidentally left in the storage and then tried to decrypt, but I doubt it since I clear my storage before killing the app.

**Comment by helios175** [comment]
Or in case you want to generate a secure key from a password or similar (provided by the user), you can use:

PasswordBasedKeyDerivation.

It's basically a wrapper around the standard PBKDF2.
You give:
- a password
- a salt that you need to store somewhere or derive... it prevents attacks based on analyzing several different keys.
- iterations (you can use the defaults)
- key length: use 16 for key, 64 for Mac.

**Comment by helios175** [comment]
Oh, ok. I get it.
So when you wipe it's ok to wipe everything. Cool.

In that case you need to check that key for encryption is the same as kep for decryption. Does that happen in any case?

**Comment by originx** [comment]
That would happen if I reinitialize the SharedPrefKeychain and the key is not there.  I keep them as singletons during app lifetime.  But I will double check all your suggestions tommorow and get back to you asap,  thank you for your time!

**Comment by helios175** [comment]
I'm thinking that there's one case that could be a problem.

If you:
1 - use the crypto/keychain
2 - wipe everything
3 - encrypt one more thing
4 - close app
5 - open app...

Step (2) removes the key from storage. But the KeyChain object will still have the old key stored in memory. Then step (3) will call the KeyChain and it will return that old key (which is not stored anymore). When you open the app (5) and try to decrypt, KeyChain won't find any stored key, and will create a new one.

So if that's the case: I would recommend getting rid of the Crypto object when you wipe data in storage. That way when you use the crypto again in (3) it will use a new Crypto and KeyChain, and it will check the storage. It'll be empty so a new key will be created and stored.

**Comment by ir2pid** [comment]
For us, adding Base64 encoding of the byte array solved the problem, will test functionality in different scenarios as mentioned above and update. 
Invalidation of privatekey on clearing the cache is desirable for our use-case.

**Comment by originx** [comment]
I can also confirm that when wiping the shared prefs, clearing the keys is important to avoid the issue @helios175  mentioned (nice hunch!)

```
mSharedPrefManager.clear();

 mSharedPrefsBackedKeyChain.destroyKeys();
```


 this is important note to **destroy** the keys as soon as wiping everything to avoid accidentally writing to the storage with old keys that are kept in mem

thank you for your time guys

**Comment by helios175** [comment]
Great! Glad to hear!

**Comment by toutoumu** [comment]
那就是说我卸载了APP (wipe everything) , 我的文件就永远无法再解密了.
