### ISSUE TITLE
libconceal.so: has text relocations with 1.0.6

### ISSUE THREAD

**Issue by PRosenb** [facebook/conceal#141]
When using
`compile 'com.facebook.conceal:conceal:1.0.5@aar'`
in build.gradle, the app runs fine.
But when the version is increased to 1.0.6, it does not run anymore on Genymotion emulators.
`compile 'com.facebook.conceal:conceal:1.0.6@aar'`

Error output:
`com.facebook.crypto.exception.KeyChainException: java.lang.UnsatisfiedLinkError: dlopen failed: .../lib/x86/libconceal.so: has text relocations`

**Comment by helios175** [comment]
Is the emulator running Android 6? It did happen to me on Android 6, but not previous.

**Comment by PRosenb** [comment]
Yes, it's an Android 6 emulator. But it worked on the same emulator with version 1.0.5 and stopped to work with 1.0.6. That's why it looks like there got something broken with 1.0.6.

**Comment by helios175** [comment]
Yes, it worked because with the new version we recompiled the included OpenSSL and there is a missing option (one that avoids producing those text relocations).

I confirmed with manual tests that regenerating OpenSSL with that option solves the problem. I will make some more tests by correctin the build scripts and building the whole thing again.

There should be a new fixed version for tomorrow.
In the meantime, you can use a nasty but very easy workaround that is changing targetVersion in your gradle file to API 22 (only for testing on Android 6! if needed!).

**Comment by PRosenb** [comment]
Many thanks for the quick answer. Great to hear that you found the cause already.
No problem with testing, I just didn't want to release the app with this problem because I'm not 100% sure that it's not affecting any real device.

**Comment by helios175** [comment]
You can try with conceal 1.0.7. It's already available through Maven.
It's just 1.0.6 with the right compilation flags so there's no text relocations (it works in Android 6, and it doesn't fire warnings in previous versions).

**Comment by PRosenb** [comment]
Thanks for the fix, I updated to 1.0.7 and it works fine.
