### ISSUE TITLE
Unexpected crypto version

### ISSUE THREAD

**Issue by ParkHanbum** [facebook/conceal#148]
05-27 18:57:44.775: W/System.err(28573): java.io.IOException: Unexpected crypto version -15

using javax.crypto.Cipher when encrypt. 
cannot decrypt by conceal.
conceal does not support java crypto?

best regard, thanks

**Comment by originx** [comment]
Hello,

we also noticed same issue in our crash reports
Stacktrace:
Caused by java.io.IOException: Unexpected crypto version -104
       at com.facebook.crypto.util.Assertions.checkArgumentForIO(Assertions.java:29)
       at com.facebook.crypto.CipherHelper.getCipherInputStream(CipherHelper.java:53)
       at com.facebook.crypto.Crypto.decrypt(Crypto.java:135)

Device statistics:
84%  - Proximity On
100% - App In Focus
84% - Rooted
5.45 GB - FREE SPACE
265.69 MB - FREE RAM
Devices:
FP1 -model: fp1u - 50%
samsung - model: gt_i9505 - 34%
asus- model: me173x 16%
Operating Systems
>100% Android version  4
4.2.2  - 66%
4.4.2  - 34%

If you need more info let me know, if we manage to reproduce it reliably I will give feedback.

Best regards.

**Comment by ninovanhooff** [comment]
I also encountered this issue on Android 6.0.

Clearing app data 'solved' the issue. Not sure if this will happen in production since I reinstall the app a lot during development, of course. Will update when I know more

**Comment by originx** [comment]
We have this issue on production so reinstalling is sadly not an option,  did you manage to reproduce the issue?

**Comment by helios175** [comment]
The format used by conceal is proprietary.

It writes version bytes (2 bytes).
Then the data: IV, ciphertext, final-tag.

That *could* match the output by javax.cipher.Crypto if they are using all the same configuration (key length, iv length, cipher, etc). But the first 2 bytes will differ.

That's why on reading conceal says version is unexpected. Because it's reading first two bytes from IV probably.

**Comment by originx** [comment]
Hello and thanks for the additional info.

Could you please elaborate more on version key and your relation to javax.cipher.Crypto?
It is unclear to me what are version bytes, are they bound to Conceal version or generated key?

-If its the key that means keys should get corrupted or wiped but encrypted data not, not sure how can this happen(?)
-If its Conceal version, we did not change it so I doubt this is the reason.

(We don't use any other persisting encryption except Conceal, although libs that we use could persist data on their own but this does not collide with Conceal storage.)

**Comment by helios175** [comment]
Conceal produces the ciphered version like this [part: bytes]:
[version bytes: 2] [IV: 12] [ciphered content] [tag: 16]

So the first two bytes are the conceal "version" number.
The first byte is always "1". It refers to this format (just in case we add some different format in the future). The second refers to the Crypto used to encrypt. There are two options: the one that uses a 128-bits key, and the preferred one, that uses a 256-bits key. You can check CryptoConfig enum for that byte value.

Said otherwise: when you encrypt with Conceal you will find it produces all those bytes. When you decrypt with Conceal it will expect the same bytes. So it will check that first two bytes match what's expected: first byte = 1, second byte = 1 or 2 (depending on key used to decrypt).

If you are producing something in the same format with other tool than Conceal, you might add those two first bytes to the input stream so Conceal is happy reading that.

You could use a ByteArrayInputStream with a byte[2] with both values, and some kind of ConcatenatingInputStream (I'm sure there's one in Java). In that way you won't need to change your file/encrypted source.
