### ISSUE TITLE
[question] What value to use for entity_id?

### ISSUE THREAD

**Issue by ninovanhooff** [facebook/conceal#150]
Can someone explain what the use of entity_id is? Can it have any value as long as the same is used for encryption/decryption? Does it have something to do with versioning?

Also the code sample in readme.md suggests that there is a 1-parameter overload of `encrypt(bute[] plaintText)`. This example seems outdated.

**Comment by siyengar** [comment]
Let me present an example, lets say a file1 is encrypted as file1.txt and file2 is encrypted as file2.txt and stored on a publicly accessible storage. An attacker could swap file1.txt and file2.txt to make the app think that file2 is actually file1. The entity id is meant to give an application identifier to the encrypted content, so that it doesn't depend on how the file is stored and if the file is swapped, the app will be able to detect that case.

**Comment by ninovanhooff** [comment]
Thanks! What will happen if I the entity_id supplied for decrypting is not equal to the one used for encrypting? Will an exception be thrown? If, instead,  data is returned, how do I detect the mismatch?

**Comment by siyengar** [comment]
Yes an exception will be thrown. We don't throw a specific exception that id didn't match. It will currently throw a "could not decrypt" error

**Comment by ninovanhooff** [comment]
Thanks again, that's all I need to know
