### ISSUE TITLE
RandomAccessFile with Conceal

### ISSUE THREAD

**Issue by hisankaran** [facebook/conceal#156]
I need to seek and read/write from a particuIar offset. I am wondering is it possible to use [RandomAccessFile](https://developer.android.com/reference/java/io/RandomAccessFile.html) with Conceal?

**Comment by helios175** [comment]
Hello, for now there's nothing about random access, as the encryption primitives we use are sequential. That's why we always wrap Input/OutputStreams.

Nevertheless that would be an interesting idea and you're not alone in being interested in it. We could try to build something to allow a more random access approach based on independent blocks, and adding a small overhead as seeking would need to start from the beginning of the block. On the security side of things, it's important the design decisions about including metadata overhead or not, and if not, what mechanism to generate IVs. It's important to choose the right policy.

It's definitely doable although I would need to squeeze it with other work I'm on right now (conceal and others). It wouldn't be transparently adding that to RandomAccessFile but to a similar interface of course (or there could be a version that offers sequential streams + seeking).

I would not expect this feature to be out before end of year.

Thanks for the interest!

**Comment by KarimFikani** [comment]
Any updates regarding supporting RandomAccessFile?
