### ISSUE TITLE
video encrypt is slow

### ISSUE THREAD

**Issue by rainmeterLotus** [facebook/conceal#162]
I want encrypt a video about 190M! the time is long,is about 30s!
there have way to optimize it??

**Comment by sinha-abhishek** [comment]
I think you should not be encrypting the entire video. You can just encrypt the headers and change them, thus no videoplayer will be able to recognize it. Before playing you can just decrypt the headers. You can see a sample implementation with conceal and exoplayer here at https://github.com/sinha-abhishek/concealwithexo

**Comment by helios175** [comment]
As Sinha says I would try to compromise on what to encrypt. I couldn't say what part of the content is enough to encrypt, but that's definitely a way. Another option is to try 128-bits key as it's faster. Use `Conceal.get().createCrypto128Bits()`.

Note: if you are just decrypting the whole video (or encrypting the whole video) and then playing it... that's a problem because video size is not bounded, it grows with duration. So I would try a on-the-fly thing (decrypting/encrypting while playing).

Another rad thing that comes to my mind is this:
- decryption is hard on CPU
- video can be hard on CPU, but reading from disk is also a containing issue

So I would try to have different threads: one for reading from disk, another for decryption and even maybe another for video processing. Most phones will have 2 or more cores.

Depending on the video library you're using everything might happen (video decoding, and disk reading) in the same thread.

If you have your video library reading from an INputStream like interface (like ExoPlayer and its Datasource's) then you could consume your data from a queue (that queue being a queue of byte[] or even better a ByteBuffer... thou I'm not very familiar with its API).

Then you have an independent thread, which needs to be notified of what to decrypt and that thread will just read from disk and decrypt into the queue).

Last mile: doing the reading in yet another thread.

So something along the lines of:

```
play video(final file/url) {
final freeChunks = create Queue with N byte[] // (short number) so buffers are reused
final dataQueue = create Queue of byte[] (or ByteBuffer)
TheradPool.submit(new Thread() {
    // this thread will read, decrypt and push to queue
    stream = open file/url
    decryptedStream = conceal....wrap(stream)
    while (!eof()) {
       chunk = freeChunks.take()
       read chunk 
       dataQueue.put(chunk)
       // this reads UPTO the size of buffer but can be less... probably it's ok
       // an option to check is using a ByteBuffer, but not sure about the API or cost of copying from stream
    });
}
```

If you not only want to read/decrypt in a separate thread than video decoding, but you also want to get reading and decrypting apart I would make that a feature.

Let's create a OtherThreadRead extends InputStream.
This Stream would consume data from yet another queue.
That queue would be fed by yet another thread reading from disk/network and putting.
Again: not sure if the gain is significative here or not. I would try not to make it super complex until you see it's totally needed.

Last time I checked encrypting 100KB in a modest phone (using 128 bits key) took 3ms. For 190MB it should be around 6s.

If what you're doing is just encrypting or decrypting a really big file.
I would try to separate the different blocking things:
- reading from disk
- encrypting/decrypting
- writing to disk

Following the same idea:
create a free buffer queue with some few byte[8192] // or similar

ThreadReader should be in a loop:
- getting a free buffer (from a queue)
- reading from the file stream
- putting that buffer into Threadcrypt

ThreadEncrypt should be in a loop:
- getting a used buffer (with probably a count attached)
- calling stream.write(buffer, 0, count)
-- the wrapped outputstream should not be a typical one but a OtherThreadWriteStream

OtherTheradWriteStream.write(buffer...) {
   puts buffer and count into a writing queue
}

ThreadWriting loops and:
- gets buffer (and count) from writing queue
- calls filestream.write(buffer, 0, count)
- offers buffer to free buffer queue
