### ISSUE TITLE
why entity is used?

### ISSUE THREAD

**Issue by vishnu229** [facebook/conceal#57]
Hi,
 I  would like to know,why entity is used.Because while encrypt i used entity as test and decrypt as 'test1' but got correct output.Please let me know why that is used?
       Thanks in Advance

**Comment by siyengar** [comment]
Lets say we have 2 files: cat.gif and dog.gif, and both of them are encrypted on disk. An attacker could technically change cat.gif to be the contents of dog.gif and the application would not know the difference. Entity allows the application to provide cryptographic binding between the name of the file and the contents so that we can detect if someone changes the name of the file. Does that answer your question?

**Comment by vishnu229** [comment]
thank u.. Entity name should be confidential?not to be hardcoded in the code?

**Comment by siyengar** [comment]
Entity name will be public. Think of it as the same as the filename. The filename is already public since it is on disk. Do not store confidential info in the Entity.

**Comment by hoonkai** [comment]
So if the name of the Entity is bound to the file name and content, then how come a file encrypted using 'test' can be decrypted using 'test1'?
