### ISSUE TITLE
Decrypting using an external tool

### ISSUE THREAD

**Issue by hoonkai** [facebook/conceal#95]
Could a file encrypted using Conceal be decrypted using an external tool? My understanding (possibly incorrect) is that the Entity information is embedded into the encrypted file. If that's the case, other tools will not appreciate the Entity information and will fail to decrypt. 

Am I missing something? 

Thanks

**Comment by frame86** [comment]
+1

**Comment by helios175** [comment]
It can be decrypted as the output format when encrypting is:
- 1 byte for format (current always 1)
- 1 byte for cipher ID (it can be 1 or 2: 128 or 256 bits key)
- IV (see CryptoConfig for correct length)
- ciphered content
- last N bytes, the integrity check tag (see CryptoConfig.tagLength)

As you can see, you can skip first two bytes and the rest will be a proper encrypted message. It's AES/GCM (128 or 256 bits).

To be completely clear:
- IV is a random value generated when encrypting, so two different encryption with know values cannot help an attacker to deduct the key
- integrity check TAG is a hash generated that depends on KEY, IV and Entity.

Entity: it's not included but it's some known value. It's not intended to be a secret. Integrity check uses this so tampering is not possible. Imagine you have a cache with two files: F1 and F2. An attacker could switch the content. But if app reads F1 with entity "F1", the integrity check will fail (because the content is in fact what was encrypted into F2). That's why we use entities. In cipher literature you will see this mechanism as AAD.

So if you encrypt something and want to decrypt it with something different you will need:
- the encrypted content (minus 2 first bytes)
- the KEY: be careful how you share this
- the Entity: this is ok to be known.

If you need bytes for the Entity/AAD then use Entity.getBytes().
In first versions of conceal it was the stringValue.getBytes("UTF-16"): this yielded some inconsistencies as it's platform dependent, so we switched to stringValue.getBytes("UTF-8") which is independent (and incidentally a little more uniform distribution).
