### ISSUE TITLE
32/64 bytes key length

### ISSUE THREAD

**Issue by anotherdev** [facebook/conceal#98]
What is the best approach to support key length of 32 or 64 bytes?

**Comment by helios175** [comment]
Currently we support 128-bits and 256-bits keys. This means 16 and 32 bytes keys.

To add support for 64bytes there should be some code in native to choose the appropriate OpenSSL primitives, besides declaring the new format as ID=3 in CryptoConfig.

You already can use 32 byte keys. Support for 64 bytes can be added to the wishlist and added later. I wouldn't recommend sending a pull request right now because we are preparing a native code overhaul, which will benefit C++ and other languages.
